blank_issues_enabled: true
contact_links:
  - name: 画面製造
    about: made by config.yml
    url: https://github.com/IES-ishikawa/todo/issues/new?template=coding.md&projects=IES-ishikawa%2Ftodo%2F1&labels=開発
